version: '3.3'
services:
  api:
    container_name: api_server
    build:
      context: ../
      dockerfile: deploy/dev/services/api/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - api:/usr/src/rhododendron_app/
    depends_on:
      - mongo
    networks:
      - backend

  mongo:
    build: dev/services/mongo/
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=api_test
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=dev
    ports:
      - 27017:27017
    volumes:
      - mongodb:/usr/src/rhododendron_db/
    networks:
      - backend

volumes:
  api:
  mongodb:

networks:
  backend:
    driver: bridge